version: '3.8'

services:
  service1:
    build: ./service
    ports:
      - "3001:3000"
    environment:
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    networks:
      - backend

  service2:
    build: ./service
    ports:
      - "3002:3000"
    environment:
      - PORT=3002
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    networks:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
